format `src/` to adhere to editorconfig (`eclint fix src/`)

diff --git a/src/thirdparty/protobuf-2.3.0/missing b/src/thirdparty/protobuf-2.3.0/missing
--- a/src/thirdparty/protobuf-2.3.0/missing
+++ b/src/thirdparty/protobuf-2.3.0/missing
@@ -116,22 +116,22 @@ case $1 in
 
   tar)
     if test -n "$run"; then
-       echo 1>&2 "ERROR: \`tar' requires --run"
-       exit 1
+        echo 1>&2 "ERROR: \`tar' requires --run"
+        exit 1
     elif test "x$2" = "x--version" || test "x$2" = "x--help"; then
-       exit 1
+        exit 1
     fi
     ;;
 
   *)
     if test -z "$run" && ($1 --version) > /dev/null 2>&1; then
-       # We have it, but it failed.
-       exit 1
+        # We have it, but it failed.
+        exit 1
     elif test "x$2" = "x--version" || test "x$2" = "x--help"; then
-       # Could not run --version or --help.  This is probably someone
-       # running `$TOOL --version' or `$TOOL --help' to check whether
-       # $TOOL exists and not knowing $TOOL uses missing.
-       exit 1
+        # Could not run --version or --help.  This is probably someone
+        # running `$TOOL --version' or `$TOOL --help' to check whether
+        # $TOOL exists and not knowing $TOOL uses missing.
+        exit 1
     fi
     ;;
 esac
@@ -142,36 +142,36 @@ case $1 in
   aclocal*)
     echo 1>&2 "\
 WARNING: \`$1' is $msg.  You should only need it if
-         you modified \`acinclude.m4' or \`${configure_ac}'.  You might want
-         to install the \`Automake' and \`Perl' packages.  Grab them from
-         any GNU archive site."
+        you modified \`acinclude.m4' or \`${configure_ac}'.  You might want
+        to install the \`Automake' and \`Perl' packages.  Grab them from
+        any GNU archive site."
     touch aclocal.m4
     ;;
 
   autoconf)
     echo 1>&2 "\
 WARNING: \`$1' is $msg.  You should only need it if
-         you modified \`${configure_ac}'.  You might want to install the
-         \`Autoconf' and \`GNU m4' packages.  Grab them from any GNU
-         archive site."
+        you modified \`${configure_ac}'.  You might want to install the
+        \`Autoconf' and \`GNU m4' packages.  Grab them from any GNU
+        archive site."
     touch configure
     ;;
 
   autoheader)
     echo 1>&2 "\
 WARNING: \`$1' is $msg.  You should only need it if
-         you modified \`acconfig.h' or \`${configure_ac}'.  You might want
-         to install the \`Autoconf' and \`GNU m4' packages.  Grab them
-         from any GNU archive site."
+        you modified \`acconfig.h' or \`${configure_ac}'.  You might want
+        to install the \`Autoconf' and \`GNU m4' packages.  Grab them
+        from any GNU archive site."
     files=`sed -n 's/^[ ]*A[CM]_CONFIG_HEADER(\([^)]*\)).*/\1/p' ${configure_ac}`
     test -z "$files" && files="config.h"
     touch_files=
     for f in $files; do
-      case $f in
-      *:*) touch_files="$touch_files "`echo "$f" |
-				       sed -e 's/^[^:]*://' -e 's/:.*//'`;;
-      *) touch_files="$touch_files $f.in";;
-      esac
+    case $f in
+    *:*) touch_files="$touch_files "`echo "$f" |
+                        sed -e 's/^[^:]*://' -e 's/:.*//'`;;
+    *) touch_files="$touch_files $f.in";;
+    esac
     done
     touch $touch_files
     ;;
@@ -179,130 +179,130 @@ WARNING: \`$1' is $msg.  You should only need it if
   automake*)
     echo 1>&2 "\
 WARNING: \`$1' is $msg.  You should only need it if
-         you modified \`Makefile.am', \`acinclude.m4' or \`${configure_ac}'.
-         You might want to install the \`Automake' and \`Perl' packages.
-         Grab them from any GNU archive site."
+        you modified \`Makefile.am', \`acinclude.m4' or \`${configure_ac}'.
+        You might want to install the \`Automake' and \`Perl' packages.
+        Grab them from any GNU archive site."
     find . -type f -name Makefile.am -print |
-	   sed 's/\.am$/.in/' |
-	   while read f; do touch "$f"; done
+        sed 's/\.am$/.in/' |
+        while read f; do touch "$f"; done
     ;;
 
   autom4te)
     echo 1>&2 "\
 WARNING: \`$1' is needed, but is $msg.
-         You might have modified some files without having the
-         proper tools for further handling them.
-         You can get \`$1' as part of \`Autoconf' from any GNU
-         archive site."
+        You might have modified some files without having the
+        proper tools for further handling them.
+        You can get \`$1' as part of \`Autoconf' from any GNU
+        archive site."
 
     file=`echo "$*" | sed -n "$sed_output"`
     test -z "$file" && file=`echo "$*" | sed -n "$sed_minuso"`
     if test -f "$file"; then
-	touch $file
+    touch $file
     else
-	test -z "$file" || exec >$file
-	echo "#! /bin/sh"
-	echo "# Created by GNU Automake missing as a replacement of"
-	echo "#  $ $@"
-	echo "exit 0"
-	chmod +x $file
-	exit 1
+    test -z "$file" || exec >$file
+    echo "#! /bin/sh"
+    echo "# Created by GNU Automake missing as a replacement of"
+    echo "#  $ $@"
+    echo "exit 0"
+    chmod +x $file
+    exit 1
     fi
     ;;
 
   bison|yacc)
     echo 1>&2 "\
 WARNING: \`$1' $msg.  You should only need it if
-         you modified a \`.y' file.  You may need the \`Bison' package
-         in order for those modifications to take effect.  You can get
-         \`Bison' from any GNU archive site."
+        you modified a \`.y' file.  You may need the \`Bison' package
+        in order for those modifications to take effect.  You can get
+        \`Bison' from any GNU archive site."
     rm -f y.tab.c y.tab.h
     if test $# -ne 1; then
         eval LASTARG="\${$#}"
-	case $LASTARG in
-	*.y)
-	    SRCFILE=`echo "$LASTARG" | sed 's/y$/c/'`
-	    if test -f "$SRCFILE"; then
-	         cp "$SRCFILE" y.tab.c
-	    fi
-	    SRCFILE=`echo "$LASTARG" | sed 's/y$/h/'`
-	    if test -f "$SRCFILE"; then
-	         cp "$SRCFILE" y.tab.h
-	    fi
-	  ;;
-	esac
+    case $LASTARG in
+    *.y)
+        SRCFILE=`echo "$LASTARG" | sed 's/y$/c/'`
+        if test -f "$SRCFILE"; then
+            cp "$SRCFILE" y.tab.c
+        fi
+        SRCFILE=`echo "$LASTARG" | sed 's/y$/h/'`
+        if test -f "$SRCFILE"; then
+            cp "$SRCFILE" y.tab.h
+        fi
+    ;;
+    esac
     fi
     if test ! -f y.tab.h; then
-	echo >y.tab.h
+    echo >y.tab.h
     fi
     if test ! -f y.tab.c; then
-	echo 'main() { return 0; }' >y.tab.c
+    echo 'main() { return 0; }' >y.tab.c
     fi
     ;;
 
   lex|flex)
     echo 1>&2 "\
 WARNING: \`$1' is $msg.  You should only need it if
-         you modified a \`.l' file.  You may need the \`Flex' package
-         in order for those modifications to take effect.  You can get
-         \`Flex' from any GNU archive site."
+        you modified a \`.l' file.  You may need the \`Flex' package
+        in order for those modifications to take effect.  You can get
+        \`Flex' from any GNU archive site."
     rm -f lex.yy.c
     if test $# -ne 1; then
         eval LASTARG="\${$#}"
-	case $LASTARG in
-	*.l)
-	    SRCFILE=`echo "$LASTARG" | sed 's/l$/c/'`
-	    if test -f "$SRCFILE"; then
-	         cp "$SRCFILE" lex.yy.c
-	    fi
-	  ;;
-	esac
+    case $LASTARG in
+    *.l)
+        SRCFILE=`echo "$LASTARG" | sed 's/l$/c/'`
+        if test -f "$SRCFILE"; then
+            cp "$SRCFILE" lex.yy.c
+        fi
+    ;;
+    esac
     fi
     if test ! -f lex.yy.c; then
-	echo 'main() { return 0; }' >lex.yy.c
+    echo 'main() { return 0; }' >lex.yy.c
     fi
     ;;
 
   help2man)
     echo 1>&2 "\
 WARNING: \`$1' is $msg.  You should only need it if
-	 you modified a dependency of a manual page.  You may need the
-	 \`Help2man' package in order for those modifications to take
-	 effect.  You can get \`Help2man' from any GNU archive site."
+    you modified a dependency of a manual page.  You may need the
+    \`Help2man' package in order for those modifications to take
+    effect.  You can get \`Help2man' from any GNU archive site."
 
     file=`echo "$*" | sed -n "$sed_output"`
     test -z "$file" && file=`echo "$*" | sed -n "$sed_minuso"`
     if test -f "$file"; then
-	touch $file
+    touch $file
     else
-	test -z "$file" || exec >$file
-	echo ".ab help2man is required to generate this page"
-	exit 1
+    test -z "$file" || exec >$file
+    echo ".ab help2man is required to generate this page"
+    exit 1
     fi
     ;;
 
   makeinfo)
     echo 1>&2 "\
 WARNING: \`$1' is $msg.  You should only need it if
-         you modified a \`.texi' or \`.texinfo' file, or any other file
-         indirectly affecting the aspect of the manual.  The spurious
-         call might also be the consequence of using a buggy \`make' (AIX,
-         DU, IRIX).  You might want to install the \`Texinfo' package or
-         the \`GNU make' package.  Grab either from any GNU archive site."
+        you modified a \`.texi' or \`.texinfo' file, or any other file
+        indirectly affecting the aspect of the manual.  The spurious
+        call might also be the consequence of using a buggy \`make' (AIX,
+        DU, IRIX).  You might want to install the \`Texinfo' package or
+        the \`GNU make' package.  Grab either from any GNU archive site."
     # The file to touch is that specified with -o ...
     file=`echo "$*" | sed -n "$sed_output"`
     test -z "$file" && file=`echo "$*" | sed -n "$sed_minuso"`
     if test -z "$file"; then
-      # ... or it is the one specified with @setfilename ...
-      infile=`echo "$*" | sed 's/.* \([^ ]*\) *$/\1/'`
-      file=`sed -n '
-	/^@setfilename/{
-	  s/.* \([^ ]*\) *$/\1/
-	  p
-	  q
-	}' $infile`
-      # ... or it is derived from the source name (dir/f.texi becomes f.info)
-      test -z "$file" && file=`echo "$infile" | sed 's,.*/,,;s,.[^.]*$,,'`.info
+    # ... or it is the one specified with @setfilename ...
+    infile=`echo "$*" | sed 's/.* \([^ ]*\) *$/\1/'`
+    file=`sed -n '
+    /^@setfilename/{
+    s/.* \([^ ]*\) *$/\1/
+    p
+    q
+    }' $infile`
+    # ... or it is derived from the source name (dir/f.texi becomes f.info)
+    test -z "$file" && file=`echo "$infile" | sed 's,.*/,,;s,.[^.]*$,,'`.info
     fi
     # If the file does not exist, the user really needs makeinfo;
     # let's fail without touching anything.
@@ -317,42 +317,42 @@ WARNING: \`$1' is $msg.  You should only need it if
     # Look for gnutar/gtar before invocation to avoid ugly error
     # messages.
     if (gnutar --version > /dev/null 2>&1); then
-       gnutar "$@" && exit 0
+        gnutar "$@" && exit 0
     fi
     if (gtar --version > /dev/null 2>&1); then
-       gtar "$@" && exit 0
+        gtar "$@" && exit 0
     fi
     firstarg="$1"
     if shift; then
-	case $firstarg in
-	*o*)
-	    firstarg=`echo "$firstarg" | sed s/o//`
-	    tar "$firstarg" "$@" && exit 0
-	    ;;
-	esac
-	case $firstarg in
-	*h*)
-	    firstarg=`echo "$firstarg" | sed s/h//`
-	    tar "$firstarg" "$@" && exit 0
-	    ;;
-	esac
+    case $firstarg in
+    *o*)
+        firstarg=`echo "$firstarg" | sed s/o//`
+        tar "$firstarg" "$@" && exit 0
+        ;;
+    esac
+    case $firstarg in
+    *h*)
+        firstarg=`echo "$firstarg" | sed s/h//`
+        tar "$firstarg" "$@" && exit 0
+        ;;
+    esac
     fi
 
     echo 1>&2 "\
 WARNING: I can't seem to be able to run \`tar' with the given arguments.
-         You may want to install GNU tar or Free paxutils, or check the
-         command line arguments."
+        You may want to install GNU tar or Free paxutils, or check the
+        command line arguments."
     exit 1
     ;;
 
   *)
     echo 1>&2 "\
 WARNING: \`$1' is needed, and is $msg.
-         You might have modified some files without having the
-         proper tools for further handling them.  Check the \`README' file,
-         it often tells you about the needed prerequisites for installing
-         this package.  You may also peek at any GNU archive site, in case
-         some other package would contain this missing \`$1' program."
+        You might have modified some files without having the
+        proper tools for further handling them.  Check the \`README' file,
+        it often tells you about the needed prerequisites for installing
+        this package.  You may also peek at any GNU archive site, in case
+        some other package would contain this missing \`$1' program."
     exit 1
     ;;
 esac
