format `src/` to adhere to editorconfig (`eclint fix src/`)

diff --git a/src/thirdparty/protobuf-2.6.1/missing b/src/thirdparty/protobuf-2.6.1/missing
--- a/src/thirdparty/protobuf-2.6.1/missing
+++ b/src/thirdparty/protobuf-2.6.1/missing
@@ -109,20 +109,20 @@ program_details ()
 {
   case $1 in
     aclocal|automake)
-      echo "The '$1' program is part of the GNU Automake package:"
-      echo "<$gnu_software_URL/automake>"
-      echo "It also requires GNU Autoconf, GNU m4 and Perl in order to run:"
-      echo "<$gnu_software_URL/autoconf>"
-      echo "<$gnu_software_URL/m4/>"
-      echo "<$perl_URL>"
-      ;;
+    echo "The '$1' program is part of the GNU Automake package:"
+    echo "<$gnu_software_URL/automake>"
+    echo "It also requires GNU Autoconf, GNU m4 and Perl in order to run:"
+    echo "<$gnu_software_URL/autoconf>"
+    echo "<$gnu_software_URL/m4/>"
+    echo "<$perl_URL>"
+    ;;
     autoconf|autom4te|autoheader)
-      echo "The '$1' program is part of the GNU Autoconf package:"
-      echo "<$gnu_software_URL/autoconf/>"
-      echo "It also requires GNU m4 and Perl in order to run:"
-      echo "<$gnu_software_URL/m4/>"
-      echo "<$perl_URL>"
-      ;;
+    echo "The '$1' program is part of the GNU Autoconf package:"
+    echo "<$gnu_software_URL/autoconf/>"
+    echo "It also requires GNU m4 and Perl in order to run:"
+    echo "<$gnu_software_URL/m4/>"
+    echo "<$perl_URL>"
+    ;;
   esac
 }
 
@@ -139,68 +139,68 @@ give_advice ()
   configure_deps="'configure.ac' or m4 files included by 'configure.ac'"
   case $normalized_program in
     autoconf*)
-      echo "You should only need it if you modified 'configure.ac',"
-      echo "or m4 files included by it."
-      program_details 'autoconf'
-      ;;
+    echo "You should only need it if you modified 'configure.ac',"
+    echo "or m4 files included by it."
+    program_details 'autoconf'
+    ;;
     autoheader*)
-      echo "You should only need it if you modified 'acconfig.h' or"
-      echo "$configure_deps."
-      program_details 'autoheader'
-      ;;
+    echo "You should only need it if you modified 'acconfig.h' or"
+    echo "$configure_deps."
+    program_details 'autoheader'
+    ;;
     automake*)
-      echo "You should only need it if you modified 'Makefile.am' or"
-      echo "$configure_deps."
-      program_details 'automake'
-      ;;
+    echo "You should only need it if you modified 'Makefile.am' or"
+    echo "$configure_deps."
+    program_details 'automake'
+    ;;
     aclocal*)
-      echo "You should only need it if you modified 'acinclude.m4' or"
-      echo "$configure_deps."
-      program_details 'aclocal'
-      ;;
-   autom4te*)
-      echo "You might have modified some maintainer files that require"
-      echo "the 'autom4te' program to be rebuilt."
-      program_details 'autom4te'
-      ;;
+    echo "You should only need it if you modified 'acinclude.m4' or"
+    echo "$configure_deps."
+    program_details 'aclocal'
+    ;;
+    autom4te*)
+    echo "You might have modified some maintainer files that require"
+    echo "the 'autom4te' program to be rebuilt."
+    program_details 'autom4te'
+    ;;
     bison*|yacc*)
-      echo "You should only need it if you modified a '.y' file."
-      echo "You may want to install the GNU Bison package:"
-      echo "<$gnu_software_URL/bison/>"
-      ;;
+    echo "You should only need it if you modified a '.y' file."
+    echo "You may want to install the GNU Bison package:"
+    echo "<$gnu_software_URL/bison/>"
+    ;;
     lex*|flex*)
-      echo "You should only need it if you modified a '.l' file."
-      echo "You may want to install the Fast Lexical Analyzer package:"
-      echo "<$flex_URL>"
-      ;;
+    echo "You should only need it if you modified a '.l' file."
+    echo "You may want to install the Fast Lexical Analyzer package:"
+    echo "<$flex_URL>"
+    ;;
     help2man*)
-      echo "You should only need it if you modified a dependency" \
-           "of a man page."
-      echo "You may want to install the GNU Help2man package:"
-      echo "<$gnu_software_URL/help2man/>"
+    echo "You should only need it if you modified a dependency" \
+            "of a man page."
+    echo "You may want to install the GNU Help2man package:"
+    echo "<$gnu_software_URL/help2man/>"
     ;;
     makeinfo*)
-      echo "You should only need it if you modified a '.texi' file, or"
-      echo "any other file indirectly affecting the aspect of the manual."
-      echo "You might want to install the Texinfo package:"
-      echo "<$gnu_software_URL/texinfo/>"
-      echo "The spurious makeinfo call might also be the consequence of"
-      echo "using a buggy 'make' (AIX, DU, IRIX), in which case you might"
-      echo "want to install GNU make:"
-      echo "<$gnu_software_URL/make/>"
-      ;;
+    echo "You should only need it if you modified a '.texi' file, or"
+    echo "any other file indirectly affecting the aspect of the manual."
+    echo "You might want to install the Texinfo package:"
+    echo "<$gnu_software_URL/texinfo/>"
+    echo "The spurious makeinfo call might also be the consequence of"
+    echo "using a buggy 'make' (AIX, DU, IRIX), in which case you might"
+    echo "want to install GNU make:"
+    echo "<$gnu_software_URL/make/>"
+    ;;
     *)
-      echo "You might have modified some files without having the proper"
-      echo "tools for further handling them.  Check the 'README' file, it"
-      echo "often tells you about the needed prerequisites for installing"
-      echo "this package.  You may also peek at any GNU archive site, in"
-      echo "case some other package contains this missing '$1' program."
-      ;;
+    echo "You might have modified some files without having the proper"
+    echo "tools for further handling them.  Check the 'README' file, it"
+    echo "often tells you about the needed prerequisites for installing"
+    echo "this package.  You may also peek at any GNU archive site, in"
+    echo "case some other package contains this missing '$1' program."
+    ;;
   esac
 }
 
 give_advice "$1" | sed -e '1s/^/WARNING: /' \
-                       -e '2,$s/^/         /' >&2
+                        -e '2,$s/^/         /' >&2
 
 # Propagate the correct exit status (expected to be 127 for a program
 # not found, 63 for a program that failed due to version mismatch).
